In [4]:
# open results/grid_search_results.csv and print the best parameters
import pandas as pd

pd.read_csv('results/grid_search_results.csv').sort_values('Mean Fitness', ascending=False).head(10)

,Algorithm,Enemy Group,Run,Generation,Mean Fitness,Max Fitness,Best Solution,npopulation,gens,mutation_rate,elitism_count
759,A,1,2,29,65.619434,88.649672,[ 4.99746960e-01 4.29242789e-02 7.91974947e-...,100,30,0.01,2
757,A,1,2,27,63.785452,88.353986,[ 4.99746960e-01 4.29242789e-02 7.91974947e-...,100,30,0.01,2
758,A,1,2,28,63.444517,88.423955,[ 4.99746960e-01 4.29242789e-02 7.91974947e-...,100,30,0.01,2
756,A,1,2,26,61.405264,88.353986,[ 4.99746960e-01 4.29242789e-02 7.91974947e-...,100,30,0.01,2
755,A,1,2,25,60.713996,88.353986,[ 4.99746960e-01 4.29242789e-02 7.91974947e-...,100,30,0.01,2
511,A,1,4,21,60.443210,66.875670,[-6.91701209e-01 -3.32350414e-01 1.09375444e-...,100,30,0.01,1
512,A,1,4,22,59.977854,66.881956,[-6.91701209e-01 -3.32350414e-01 1.09375444e-...,100,30,0.01,1
509,A,1,4,19,59.647936,66.875670,[-6.91701209e-01 -3.32350414e-01 1.09375444e-...,100,30,0.01,1
518,A,1,4,28,59.490273,66.969786,[-6.91701209e-01 -3.32350414e-01 1.09375444e-...,100,30,0.01,1
508,A,1,4,18,59.445070,66.875670,[-6.91701209e-01 -3.32350414e-01 1.09375444e-...,100,30,0.01,1